####################################################
#               AutoCommand Config                 #
####################################################
# https://github.com/kieranperk/AutoCommand/wiki/Configuration

startup:
  enabled: true
  players-needed: 0
  wait-length: 5
  command-interval: 2
  commands:
    - "say [AutoCommand] Thanks for using me!"
    - "say [AutoCommand] You can set a custom interval between sending commands."
    - "say [AutoCommand] And you can add an UNLIMITED AMOUNT OF COMMANDS!"
    - ""
    - "say [AutoCommand] You can also send blank commands which don't execute anything."
